include(":app",
    ":dataprovider",
    ":aptoidepreferences",
    ":crashreports",
    ":utils",
    ":aptoide-account-manager",
    ":aptoide-database",
    ":downloadmanager",
    ":aptoide-analytics-core",
    ":aptoide-analytics-default-implementation",
    ":aptoide-views",
    ":packageinstaller",
    ":aptoide-authentication-core",
    ":aptoide-authentication-rx", ":appcoins", ":feature_apps")