package com.aptoide.android.aptoidegames.theme

import androidx.compose.ui.graphics.vector.ImageVector

data class AppIcons(
  val LeftArrow: ImageVector,
  val ToolBarLogo: ImageVector,
  val ToolBarLogoDev: ImageVector,
  val CaretRight: ImageVector,
  val PlanetSearch: ImageVector,
  val Gamepad: ImageVector,
  val SingleGamepad: ImageVector,
  val ErrorBug: ImageVector,
  val NoConnection: ImageVector,
  val ErrorOutlined: ImageVector,
  val NoConnectionSmall: ImageVector,
  val WifiDialogIcon: ImageVector,
  val NotificationBell: ImageVector,
  val HistoryOutlined: ImageVector,
  val AutoCompleteSuggestion: ImageVector,
  var Asterisk: ImageVector,
  var Bug: ImageVector,
  var Check: ImageVector,
  var CheckBox: ImageVector,
  var Close: ImageVector,
  var Error: ImageVector,
  var Games: ImageVector,
  var Gift: ImageVector,
  var Logout: ImageVector,
  var NoWifi: ImageVector,
  var Search: ImageVector,
  var Wifi: ImageVector,
  var RecentSearches: ImageVector,
  var PopularSearches: ImageVector,
  var SearchLens: ImageVector,
  var MoreVert: ImageVector,
  val Muted: ImageVector,
  val Unmuted: ImageVector,
  val GenericError: ImageVector,
  val NoNetworkError: ImageVector,
  val AptoideSetting: ImageVector
)
