@Suppress("unused")
object ModuleDependency {
  // All consts are accessed via reflection
  const val APP = ":app"
  const val INSTALL_MANAGER = ":install-manager"
  const val FEATURE_APPS = ":feature_apps"
  const val FEATURE_HOME = ":feature-home"
  const val FEATURE_SEARCH = ":feature_search"
  const val FEATURE_UPDATES = ":feature_updates"
  const val INSTALLED_APPS = ":installed_apps"
  const val APTOIDE_NETWORK = ":aptoide-network"
  const val FEATURE_APPVIEW = ":feature_appview"
  const val FEATURE_REPORT_APP = ":feature_report_app"
  const val FEATURE_EDITORIAL = ":feature_editorial"
  const val APTOIDE_UI = ":aptoide-ui"
  const val FEATURE_REACTIONS = ":feature-reactions"
  const val DOWNLOAD_VIEW = ":download-view"
  const val APTOIDE_INSTALLER = ":aptoide-installer"
  const val DOWNLOAD_MANAGER = ":downloadmanager"
  const val APTOIDE_DATABASE = ":aptoide-database"
  const val PACKAGE_INSTALLER = ":packageinstaller"
  const val UTILS = ":utils"
  const val UTIL = ":util"
  const val DOWNLOADS_DATABASE = ":downloads_database"
  const val FEATURE_CAMPAIGNS = ":feature_campaigns"
  const val FEATURE_CATEGORIES = ":feature_categories"
}
