@Suppress("unused")
object ModuleDependency {
  // All consts are accessed via reflection
  const val APP = ":app"
  const val INSTALL_MANAGER = ":install-manager"
  const val FEATURE_APPS = ":feature_apps"
  const val FEATURE_HOME = ":feature-home"
  const val FEATURE_FLAGS = ":feature-flags"
  const val PAYMENT_MANAGER = ":payments:base:payment-manager"
  const val PAYMENT_PREFS = ":payments:base:payment-prefs"
  const val OEM_EXTRACTOR = ":payments:base:oem-extractor"
  const val GUEST_WALLET = ":payments:guest-wallet"
  const val OSP_HANDLER = ":payments:osp-handler"
  const val ADYEN = ":payments:payment-methods:adyen"
  const val PAYPAL = ":payments:payment-methods:paypal"
  const val FEATURE_SEARCH = ":feature_search"
  const val FEATURE_UPDATES = ":feature_updates"
  const val APTOIDE_NETWORK = ":aptoide-network"
  const val FEATURE_APPVIEW = ":feature_appview"
  const val FEATURE_REPORT_APP = ":feature_report_app"
  const val FEATURE_EDITORIAL = ":feature_editorial"
  const val APTOIDE_UI = ":aptoide-ui"
  const val FEATURE_REACTIONS = ":feature-reactions"
  const val DOWNLOAD_VIEW = ":download-view"
  const val APTOIDE_INSTALLER = ":aptoide-installer"
  const val APTOIDE_TASK_INFO = ":aptoide-task-info"
  const val TEST = ":test"
  const val FEATURE_CAMPAIGNS = ":feature_campaigns"
  const val FEATURE_CATEGORIES = ":feature_categories"
  const val YOUTUBE_VIDEO_PLAYER = ":android-youtube-player:core"
  const val FEATURE_PROFILE = ":feature-profile"
  const val FEATURE_SETTINGS = ":feature-settings"
  const val FEATURE_OOS = ":feature-oos"
  const val ENVIRONMENT_INFO = ":environment-info"
  const val EXTENSIONS = ":extensions"
  const val NETWORK_LISTENER = ":network-listener"
}
